sudo : required
services : 
  - docker

before_install  : 
  - docker build -t lakshyapurwar/docker-react -f Dockerfile.dev .

script : 
   - docker run -e CI=true lakshyapurwar/docker-react npm run test

deploy:
  provider : elasticbeanstalk
  region : "ap-northeast-1"
  app : "frontend"
  env : "Frontend-env"
  bucket_name : "elasticbeanstalk-ap-northeast-1-162239014893"
  bucket_path : "frontend"
  on : 
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : "$AWS_SECRET_KEY"



